#!/bin/bash

echo "Please enter a number:"

read inputNumber

counter=1

for (( i=1;i<=$inputNumber;i++))
do

if [ $((i%3)) -eq 0 ] && [ $((i%5)) -eq 0 ]
then
echo "FizzBuzz!"

elif [ $((i%3)) -eq 0 ]
then
echo "Fizz!"

elif [ $((i%5)) -eq 0 ]
then
echo "Buzz!"

else
echo "${i}"
fi

done

